# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0519e290d429f78d088be266b79f7d9a25c7f9a37f0ec00cf02bc5e08f486ad92c49d4a4d0c39ee53682da36926bbe69b2357722f25e29ed4fb4fde77bef25d0

test:
  secret_key_base: 60d60f9ab6104982f146988dac328a8da01cb4c69569072ed99d63e7d4e673e9c09bed53217fa6ba8b3f89fe4dc52cf7edb053e1497084cc8f6bc3deaddf5d19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
